"""
AlgoTrade Engine — Shared Data Types
Dataclasses used across all modules for consistent data interfaces.
"""

from dataclasses import dataclass, field
from typing import Optional
import numpy as np


@dataclass
class OHLCVData:
    """Historical OHLCV price data for a single stock."""
    ticker: str
    dates: list[str]
    open: np.ndarray
    high: np.ndarray
    low: np.ndarray
    close: np.ndarray
    volume: np.ndarray

    @property
    def n(self) -> int:
        return len(self.close)

    def daily_returns(self) -> np.ndarray:
        """Compute daily percentage returns from close prices."""
        return np.diff(self.close) / self.close[:-1]


@dataclass
class TradeSignal:
    """A single trade signal generated by the Signal Engine."""
    ticker: str
    signal_type: str           # "BUY" or "SELL"
    entry_idx: int             # Index into the price array
    exit_idx: int              # Index into the price array
    entry_price: float
    exit_price: float
    expected_return: float     # Expected return (value for scheduling)
    source: str                # Which algorithm generated this signal
    entry_date: str = ""
    exit_date: str = ""

    @property
    def profit(self) -> float:
        if self.signal_type == "BUY":
            return self.exit_price - self.entry_price
        return self.entry_price - self.exit_price

    @property
    def profit_pct(self) -> float:
        return (self.profit / self.entry_price) * 100

    @property
    def duration(self) -> int:
        return self.exit_idx - self.entry_idx


@dataclass
class PortfolioAllocation:
    """Result of the portfolio construction module."""
    selected_tickers: list[str]
    weights: list[float]           # Capital fraction for each stock
    capital_allocated: list[float] # Dollar amount per stock
    total_capital_used: float
    expected_return: float
    method: str                    # "knapsack_dp", "greedy", "brute_force"


@dataclass
class BacktestResult:
    """Result of a full backtest run."""
    # Portfolio value over time
    dates: list[str]
    portfolio_values: list[float]
    cash_values: list[float]

    # Executed trades
    trades: list[dict]

    # Summary metrics
    total_return_pct: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown_pct: float = 0.0
    win_rate_pct: float = 0.0
    total_trades: int = 0
    avg_trade_duration: float = 0.0

    # Buy-and-hold comparison
    bnh_return_pct: float = 0.0
    bnh_values: list[float] = field(default_factory=list)


@dataclass
class BenchmarkResult:
    """Result of a single algorithm benchmark run."""
    algorithm_name: str
    input_sizes: list[int]
    runtimes_ms: list[float]
    theoretical_complexity: str   # e.g., "O(n log n)"
    empirical_slope: float        # Slope from log-log fit
    category: str                 # Module name


@dataclass
class AlgorithmComparison:
    """Comparison between brute-force and optimized algorithm."""
    module: str
    algorithm_name: str
    paradigm: str
    brute_force: BenchmarkResult
    optimized: BenchmarkResult
    speedup_factors: list[float]  # Speedup at each input size
