/**
 * AlgoTrade Engine — Constants & Algorithm Metadata
 */

export const COLORS = {
  blue:   '#3b82f6',
  green:  '#10b981',
  purple: '#8b5cf6',
  amber:  '#f59e0b',
  red:    '#ef4444',
  cyan:   '#06b6d4',
  pink:   '#ec4899',
  teal:   '#14b8a6',
  orange: '#f97316',
  indigo: '#6366f1',
};

export const CHART_COLORS = [
  COLORS.blue, COLORS.green, COLORS.purple, COLORS.amber,
  COLORS.cyan, COLORS.pink, COLORS.teal, COLORS.orange,
  COLORS.indigo, COLORS.red,
];

export const ALGORITHM_META = {
  segment_tree: {
    name: 'Segment Tree',
    paradigm: 'Tree Data Structure',
    brute: 'O(n)',
    optimized: 'O(log n)',
    module: 'Data Layer',
    color: COLORS.blue,
    description: 'Supports range min/max/sum queries with O(log n) per query after O(n) build.',
  },
  sparse_table: {
    name: 'Sparse Table',
    paradigm: 'Precomputation / Binary Lifting',
    brute: 'O(n)',
    optimized: 'O(1)',
    module: 'Data Layer',
    color: COLORS.cyan,
    description: 'O(1) range min/max queries after O(n log n) preprocessing using idempotent operations.',
  },
  divide_conquer: {
    name: 'Max Profit (D&C)',
    paradigm: 'Divide & Conquer',
    brute: 'O(n²)',
    optimized: 'O(n log n)',
    module: 'Signal Engine',
    color: COLORS.green,
    description: 'Finds maximum buy-sell profit via recursive midpoint split.',
  },
  kadanes: {
    name: "Kadane's Algorithm",
    paradigm: 'Dynamic Programming',
    brute: 'O(n²)',
    optimized: 'O(n)',
    module: 'Signal Engine',
    color: COLORS.purple,
    description: 'Max subarray sum in linear time using running maximum technique.',
  },
  sliding_window: {
    name: 'Sliding Window',
    paradigm: 'Sliding Window',
    brute: 'O(n·k)',
    optimized: 'O(n)',
    module: 'Signal Engine',
    color: COLORS.amber,
    description: 'SMA, EMA, RSI, Bollinger Bands computed via incremental sliding window.',
  },
  fft: {
    name: 'FFT Cycle Detection',
    paradigm: 'Transform',
    brute: 'O(n²) DFT',
    optimized: 'O(n log n) FFT',
    module: 'Signal Engine',
    color: COLORS.pink,
    description: 'Extracts dominant frequency components from price time series.',
  },
  kmp: {
    name: 'KMP Pattern Match',
    paradigm: 'String Matching',
    brute: 'O(n·m)',
    optimized: 'O(n + m)',
    module: 'Signal Engine',
    color: COLORS.teal,
    description: 'Encodes candlesticks as characters and searches for known patterns via failure function.',
  },
  rabin_karp: {
    name: 'Rabin-Karp',
    paradigm: 'Hashing',
    brute: 'O(n·m)',
    optimized: 'O(n + m) avg',
    module: 'Signal Engine',
    color: COLORS.orange,
    description: 'Rolling hash-based string matching for candlestick pattern detection.',
  },
  knapsack: {
    name: '0/1 Knapsack',
    paradigm: 'Dynamic Programming',
    brute: 'O(2ⁿ)',
    optimized: 'O(n·W)',
    module: 'Portfolio',
    color: COLORS.indigo,
    description: 'Capital allocation using DP with backtracking for optimal stock selection.',
  },
  kruskal_mst: {
    name: "Kruskal's MST",
    paradigm: 'Greedy + Graph',
    brute: 'O(V²)',
    optimized: 'O(E log E)',
    module: 'Portfolio',
    color: COLORS.green,
    description: 'Correlation-based MST for portfolio diversification maximization.',
  },
  union_find: {
    name: 'Union-Find (DSU)',
    paradigm: 'Disjoint Set',
    brute: 'O(n)',
    optimized: 'O(α(n))',
    module: 'Portfolio',
    color: COLORS.blue,
    description: "Path compression + union-by-rank for Kruskal's MST cycle detection.",
  },
  activity_selection: {
    name: 'Activity Selection',
    paradigm: 'Greedy',
    brute: 'O(2ⁿ)',
    optimized: 'O(n log n)',
    module: 'Execution',
    color: COLORS.amber,
    description: 'Selects maximum non-overlapping trades using exchange argument proof.',
  },
  max_heap: {
    name: 'Max-Heap',
    paradigm: 'Heap Data Structure',
    brute: 'O(n log n) insert',
    optimized: 'O(n) heapify',
    module: 'Execution',
    color: COLORS.red,
    description: 'Priority queue for ranking pending trade signals by expected return.',
  },
  avl_tree: {
    name: 'AVL Tree',
    paradigm: 'Balanced BST',
    brute: 'O(n) sorted list',
    optimized: 'O(log n)',
    module: 'Execution',
    color: COLORS.purple,
    description: 'Self-balancing BST for simulated limit order book operations.',
  },
  interval_scheduling: {
    name: 'Interval Scheduling',
    paradigm: 'DP + Binary Search',
    brute: 'O(2ⁿ)',
    optimized: 'O(n log n)',
    module: 'Backtester',
    color: COLORS.cyan,
    description: 'Weighted interval scheduling to maximize total return from non-conflicting trades.',
  },
};

export const MODULES = ['Data Layer', 'Signal Engine', 'Portfolio', 'Execution', 'Backtester'];
